apiVersion: v2
name: gavin
description: A Helm chart for Gavin Vinyl Library application
type: application
version: 0.2.0
appVersion: "v0.2.0"
keywords:
  - vinyl
  - music
  - catalog
  - rust
  - react
maintainers:
  - name: Gavin Team
home: https://github.com/restanrm/gavin
sources:
  - https://github.com/restanrm/gavin
